### ISSUE TITLE
Playsound unable to play the wav-files created

### ISSUE THREAD

**Issue by rontus** [zswitten/chat_out_loud_gpt#3]
Hi, after the audio response file is generated and playaudio tries to play the file, I get this error every time: `playsound.PlaysoundException:
    Error 263 for command:
        open "speech_output.wav16" alias playsound_0.5151501475155232
    The specified device is not open or is not recognized by MCI.`

I tried to run another .wav-file with playaudio and it worked fine. And manually trying to play files created by chat_out_loud_gpt failed with playsound. Those files play fine in media players I have.

I can see that the sample rate is 32000 where as my example file that worked had 44100. I wonder if this could be an issue in my playback attempts.

Win 11, Python 3.10.10
```
pip list
Package            Version
------------------ ---------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              22.2.0
certifi            2022.12.7
charset-normalizer 2.1.1
colorama           0.4.6
frozenlist         1.3.3
idna               3.4
multidict          6.0.4
openai             0.27.0
pip                23.0.1
playsound          1.2.2
PyAudio            0.2.13
requests           2.28.1
setuptools         65.6.3
tqdm               4.65.0
urllib3            1.26.15
wheel              0.38.4
wincertstore       0.2
yarl               1.8.2
```

**Comment by zswitten** [comment]
Seems like a Windows issue. Do any of the options [here](https://stackoverflow.com/questions/260738/play-audio-with-python) work for you?

**Comment by rontus** [comment]
Hi,
thanks, had just gotten around it by adding
`from pydub import AudioSegment`

and replacing
`def play_audio(path):
    playsound(path)`
with
`def play_audio(path):
    sound = AudioSegment.from_wav(path)
    player = pyaudio.PyAudio().open(format=pyaudio.paInt16, channels=1, rate=32000, output=True)
    player.write(sound.raw_data)
    player.close()`
